context = GraphMatchingContext
programConfig = gedevo
dataConfig = rashid
qualityMeasures = AlignedEdgesQualityMeasure,GraphEditDistanceQualityMeasure,EdgeCorrectnessQualityMeasure
mode = parameter_optimization
optimizationMethod = LayeredDivisiveParameterOptimizationMethod
optimizationCriterion = AlignedEdgesQualityMeasure
optimizationIterations = 10

[gedevo]
optimizationParameters = pop,maxsame
